namespace TodoApp.Api.Middleware;

// Generated by: Manus AI
using System.Text.Json;
using TodoApp.Api.Dtos; // Onde quer que seu ResponseViewModel esteja

public class GlobalExceptionHandlerMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<GlobalExceptionHandlerMiddleware> _logger;

    // O construtor recebe o próximo middleware no pipeline e um logger.
    public GlobalExceptionHandlerMiddleware(RequestDelegate next, ILogger<GlobalExceptionHandlerMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    // Este é o método principal do middleware.
    public async Task InvokeAsync(HttpContext context)
    {
        try
        {
            // Tenta executar o resto do pipeline.
            await _next(context);
        }
        catch (Exception ex)
        {
            // Se uma exceção for capturada, chama nosso método de tratamento.
            await HandleExceptionAsync(context, ex);
        }
    }

    private async Task HandleExceptionAsync(HttpContext context, Exception exception)
    {
        // 1. Logar a exceção (MUITO IMPORTANTE para produção)
        _logger.LogError(exception, "Ocorreu uma exceção não tratada: {Message}", exception.Message);

        // 2. Preparar a resposta de erro padronizada
        var errorResponse =
            new ResponseViewModel<object>(
                "Ocorreu um erro interno no servidor. Por favor, tente novamente mais tarde.");

        // 3. Configurar a resposta HTTP
        context.Response.ContentType = "application/json";
        context.Response.StatusCode = StatusCodes.Status500InternalServerError;

        // 4. Escrever a resposta JSON no corpo da resposta
        await context.Response.WriteAsync(JsonSerializer.Serialize(errorResponse));
    }
}